export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';
export const POST_FETCHING= 'POST_FETCHING';
export const POST_FETCH_ERROR = 'POST_FETCH_ERROR';